/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aptitude;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.io.*;
import java.net.*;
import sun.security.x509.X500Name;

/**
 *
 * @author Robert
 */
public class QuestionGui extends javax.swing.JFrame {

    /**
     * Creates new form Question
     */
    public QuestionGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAns = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAQ = new javax.swing.JTextArea();
        txtAns = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnAns.setText("Answer");
        btnAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnsActionPerformed(evt);
            }
        });

        txtAQ.setEditable(false);
        txtAQ.setColumns(20);
        txtAQ.setLineWrap(true);
        txtAQ.setRows(5);
        txtAQ.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtAQ);

        jLabel2.setText("If your answer is a number, type in the digits. Otherwise enter the characters");

        jLabel3.setVisible(false);
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAns, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(161, 161, 161)
                                .addComponent(btnAns, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAns)
                    .addComponent(txtAns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   public Maze m= new Maze();
   public Question q = new Question();
   public String actAns,Ans;
   public URL url;
    public void populate(String type, boolean isImage){
  //set certain components based on question type
  //Make use of image
  if(isImage){
      //resizepic();
  }
}
private Image resizepic(Image pic,int w,int h){
    BufferedImage rs = new BufferedImage(w,h,BufferedImage.TYPE_INT_RGB);
    Graphics2D g = rs.createGraphics();
    g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
    g.drawImage(pic,0,0,w,h,null);
    g.dispose();
    return rs;
}
private Image BufferedImtoIm(BufferedImage Bimage){
    return Toolkit.getDefaultToolkit().createImage(Bimage.getSource());
}
private void setImage(){
           Image image;
           if (q.getBlob()==null){
                   try { 
                     url = new URL("https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/300px-No_image_available.svg.png");
                    image = ImageIO.read(url);
                   ImageIcon icon = new ImageIcon(resizepic(image, jLabel1.getWidth(),jLabel1.getHeight()));
                 jLabel1.setIcon(icon);
         
                } catch (IOException ex) {
              Logger.getLogger(QuestionGui.class.getName()).log(Level.SEVERE, null, ex);
           }
         } else{
               InputStream in = new ByteArrayInputStream(q.getBlob());
               try {
                   BufferedImage bi = ImageIO.read(in);
                   image = BufferedImtoIm(bi);
                   ImageIcon icon = new ImageIcon(resizepic(image, jLabel1.getWidth(),jLabel1.getHeight()));
                   jLabel1.setIcon(icon);

               } catch (IOException ex) {
                   Logger.getLogger(QuestionGui.class.getName()).log(Level.SEVERE, null, ex);
               }
           }

}
    private void proceed(){
       boolean random = StartPage.userdb.addQuestionToListOfCorrectQuestions(q, Ans);
       
       this.setVisible(false);
       m.qcount++;
       m.nextQ(m.qcount);
       
    }
    private boolean IsNumber(String s){

        for (int i = 0; i < s.length(); i++) {
            if(!Character.isDigit(s.charAt(i))) {  
                return false;
            }        
        }
        return true;
    }
    private void btnAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnsActionPerformed
        // TODO add your handling code here:
//        check answer, update score
        Ans = txtAns.getText();
      actAns = q.getAnswer();
      jLabel3.setVisible(false);
    if(IsNumber(actAns)&&IsNumber(Ans)){
     proceed();
    }
    else if(!IsNumber(actAns)&&!IsNumber(Ans)){
        proceed();
    }
    else {
        if(IsNumber(actAns)){
         //JOptionPane.showMessageDialog(null,"Please enter a number");
         jLabel3.setText("Please enter a number");
         jLabel3.setVisible(true);
        }
        else if(!(IsNumber(actAns))){
         // JOptionPane.showMessageDialog(null,"Please enter a word or sentence"); 
         jLabel3.setText("Please enter a word or sentence");
         jLabel3.setVisible(true);
        }
    }

       
    }//GEN-LAST:event_btnAnsActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        setLocationRelativeTo(null);
        jLabel3.setVisible(false);
        q=  StartPage.userdb.getNextQuestion("EASY");
        txtAQ.setText("Question: "+m.qcount+"\n"+ q.getQuestion());
        setImage();
        txtAns.setText("");
      // m.arrbut[0]=true;

//            
//       setExtendedState(JFrame.MAXIMIZED_BOTH); 
//        setUndecorated(true);
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAns;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAQ;
    private javax.swing.JTextField txtAns;
    // End of variables declaration//GEN-END:variables
}
